
// This file has been generated by the GUI designer. Do not modify.
namespace MonoSerial
{
	public partial class SettingsDialog
	{
		private global::Gtk.RadioButton optAppendNothing;

		private global::Gtk.RadioButton optAppendCR;

		private global::Gtk.RadioButton optAppendLF;

		private global::Gtk.RadioButton optAppendCRLF;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MonoSerial.SettingsDialog
			this.Name = "MonoSerial.SettingsDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child MonoSerial.SettingsDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.optAppendNothing = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Append nothing"));
			this.optAppendNothing.CanFocus = true;
			this.optAppendNothing.Name = "optAppendNothing";
			this.optAppendNothing.DrawIndicator = true;
			this.optAppendNothing.UseUnderline = true;
			this.optAppendNothing.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			w1.Add(this.optAppendNothing);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1[this.optAppendNothing]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.optAppendCR = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Append CR"));
			this.optAppendCR.CanFocus = true;
			this.optAppendCR.Name = "optAppendCR";
			this.optAppendCR.DrawIndicator = true;
			this.optAppendCR.UseUnderline = true;
			this.optAppendCR.Group = this.optAppendNothing.Group;
			w1.Add(this.optAppendCR);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1[this.optAppendCR]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.optAppendLF = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Append LF"));
			this.optAppendLF.CanFocus = true;
			this.optAppendLF.Name = "optAppendLF";
			this.optAppendLF.DrawIndicator = true;
			this.optAppendLF.UseUnderline = true;
			this.optAppendLF.Group = this.optAppendNothing.Group;
			w1.Add(this.optAppendLF);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1[this.optAppendLF]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.optAppendCRLF = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Append CR+LF"));
			this.optAppendCRLF.CanFocus = true;
			this.optAppendCRLF.Name = "optAppendCRLF";
			this.optAppendCRLF.DrawIndicator = true;
			this.optAppendCRLF.UseUnderline = true;
			this.optAppendCRLF.Group = this.optAppendNothing.Group;
			w1.Add(this.optAppendCRLF);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1[this.optAppendCRLF]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Internal child MonoSerial.SettingsDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6[this.buttonCancel]));
			w7.Expand = false;
			w7.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6[this.buttonOk]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.buttonCancel.Clicked += new global::System.EventHandler(this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
